---
title: "plots_presentation"
format: html
editor: visual
---

```{r}
pacman::p_load(ggplot2,#plots
               tictoc, #timing
               dplyr, #filter 
               e1071 #skewness,
)

```

```{r}
mc <- c("#048A81","#06D6A0","#54C6EB","#8A89C0")
mycolors <- c("#06D6A0","#c5caf0","#7083fa", "#0317ad")
mycolors2 <- c("#faf5f6","#e0abb4","#ad3b50","#5e0112")
```

```{r}
n_animals <- 70000
m <- rnorm(n_animals, mean = 0, sd = 1)
h <- hist(m,
          breaks = 30,
          plot = FALSE)


h$counts <- h$counts / sum(h$counts) * 100

#this I cannot save it because it is not ggplot
plot(h,
     col = mc[1],
     border = "white",
     main = "Distribution of temperature ~ N(0, 1)",
     xlab = "Temperature",
     ylab = "Percentage (%)")

```

```{r}
set.seed(42)
betas <- rnorm(4, mean = 1, sd = 0.3)

x <- seq(-2, 2, length.out = 100)
df <- expand.grid(x = x, line = 1:4)
df$y <- df$x * betas[df$line]

# Plot con ggplot2
p1 <- ggplot(df, aes(x = x, y = y, group = line)) +
  geom_line(size = 1) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray") +
  coord_fixed(xlim = c(-2, 2), ylim = c(-2, 2)) +
  labs(x = "temperature", y = "trait value", title = "Reaction norm") +
  theme_minimal() +
  theme(legend.position = "none",
    axis.title.x = element_text(size = 18),
    axis.title.y = element_text(size = 18),
    axis.text.x = element_text(size = 14),  
    axis.text.y = element_text(size = 14),  
    plot.title = element_text(size = 20, face = "bold", hjust=0.5),
    strip.text = element_text(size = 16))

p_points <- data.frame(
  x = rep(1.3, 4),
  y = 1.3 * betas,
  line = 1:4
)


p1_p <- p1 +
  geom_point(data = p_points, aes(x = x, y = y), size = 3, color = mycolors)

p1_p
# ggsave("./plot_presentation/plot3.png", p1_p, width = 6, height = 6, dpi = 300)
```

```{r}
#minus temperature
set.seed(42)
betas <- rnorm(4, mean = 1, sd = 0.3)

n_points <- data.frame(
  x = rep(-0.7, 4),
  y = -0.7 * betas,
  line = 1:4
)

p1_n <- p1 +
  geom_point(data = n_points, aes(x = x, y = y), size = 3, color = mycolors)

p1_n
# ggsave("./plot_presentation/plot4.png", p1_n, width = 6, height = 6, dpi = 300)
```

```{r}

x<-seq(-2, 2, length.out = 100)
# Plot con ggplot2
p5 <- ggplot(data.frame(x = x, y = x + 0.28), aes(x,y)) +
  geom_line(size = 1) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray") +
  coord_fixed(xlim = c(-2, 2), ylim = c(-2, 2)) +
  labs(x = "trait value", y = "demographic value", title = "Trait-Demographic Relation") +
  theme_minimal() +
  theme(legend.position = "none",
    axis.title.x = element_text(size = 18),
    axis.title.y = element_text(size = 18),
    axis.text.x = element_text(size = 14),  
    axis.text.y = element_text(size = 14),  
    plot.title = element_text(size = 20, face = "bold", hjust=0.5),
    strip.text = element_text(size = 16))


demo_p_x <- p_points$y
demo_p_y <-  1 * demo_p_x + 0.28



p5_p<- p5 + geom_point(data = data.frame(x = demo_p_x, y = demo_p_y),
                     aes(x = x, y = y), size = 3, color = mycolors)
p5_p
# ggsave("./plot_presentation/plot5.png", p5_p, width = 6, height = 6, dpi = 300)
```

```{r}
demo_n_x <- n_points$y
demo_n_y <-  1 * demo_n_x + 0.28



p5_n<- p5 + geom_point(data = data.frame(x = demo_n_x, y = demo_n_y),
                     aes(x = x, y = y), size = 3, color = mycolors)
p5_n
# ggsave("./plot_presentation/plot6.png", p5_n, width = 6, height = 6, dpi = 300)
```

```{r}
set.seed(42)
x <- seq(-2.5, 2.5, length.out = 100)
df <- data.frame(x = x, y = plogis(x))


p7 <- ggplot(df, aes(x = x, y = y)) +
  geom_line(size = 1) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray") +
  xlim(-2.5,2.5) + ylim(0,1) +  # per probabilità
  labs(x = "demographic value", y = "probability of surviving", 
       title = "Probability of surviving") +
  theme_minimal() +
  theme(legend.position = "none",
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        axis.text.x = element_text(size = 14),  
        axis.text.y = element_text(size = 14),  
        plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
        strip.text = element_text(size = 16))


x_surv_p <- demo_p_x
y_surv_p <- plogis(x_surv_p)


p7_p <- p7 + geom_point(data = data.frame(x = x_surv_p, y = y_surv_p), aes(x = x, y = y), size = 3, color = mycolors)
p7_p
# ggsave("./plot_presentation/plot7.png", p7_p, width = 6, height = 6, dpi = 300)
```

```{r}
# Create a data frame for plotting
df <- data.frame(
  group = factor(1:4),
  value = y_surv_p
)

# Simple bar plot
p9<- ggplot(df, aes(x = group, y = value, fill = group)) +
  geom_bar(stat = "identity") +
  ylim(0,1)+
  
  scale_fill_manual(values = mycolors) +
  labs(x = "Animals", y = "Survival Probability",title = "Probability of surviving") +
  geom_hline(yintercept = 0.76, linetype = "dashed", color ="red")+
  theme_minimal()+
    theme(legend.position = "none",
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        axis.text.x = element_text(size = 14),  
        axis.text.y = element_text(size = 14),  
        plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
        strip.text = element_text(size = 16))
ggsave("./plot_presentation/plot10.png", p9, width = 6, height = 6, dpi = 300)
p9
```

```{r}
x_surv_n <- demo_n_x
y_surv_n <- plogis(x_surv_n)


p7_n <- p7 + geom_point(data = data.frame(x = x_surv_n, y = y_surv_n), aes(x = x, y = y), size = 3, color = mycolors)

ggsave("./plot_presentation/plot8.png", p7_n, width = 6, height = 6, dpi = 300)
```

```{r}
# Create a data frame for plotting
df <- data.frame(
  group = factor(1:4),
  value = y_surv_n
)

# Simple bar plot
p10<- ggplot(df, aes(x = group, y = value, fill = group)) +
  geom_bar(stat = "identity") +
  ylim(0,1)+
  
  scale_fill_manual(values = mycolors) +
  labs(x = "Animals", y = "Survival Probability",title = "Probability of surviving") +
  geom_hline(yintercept = 0.64, linetype = "dashed", color ="red")+
  theme_minimal()+
    theme(legend.position = "none",
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        axis.text.x = element_text(size = 14),  
        axis.text.y = element_text(size = 14),  
        plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
        strip.text = element_text(size = 16))
ggsave("./plot_presentation/plot12.png", p10, width = 6, height = 6, dpi = 300)

```
