set.seed(404)


# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialized set.seed(404)
library(dplyr)
library(data.table)


# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialize both juveniles and adults, but later only juveniles), the beta coefficient of the linear model, the standard deviation of beta (beta_sd), and a temperature value. It outputs randomly generated beta values (drawn from a Gaussian distribution centered on beta with standard deviation beta_sd) and assigns a trait to each newborn accordingly.
#The user has to provide the sd and the mean
calculate_trait <- function(
    shape, animals, int,beta, beta_sd, clim_val
) { 
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd) 
    trait_values <- int + (beta_animals * clim_val)
    
  } 
  return(trait_values)
}



#Same concept as the one before, we generate for each new animal a linear coefficient taken from a Gaussian distribution. It returns a demographic value that can be used both to calculate the probability of surviving or the number of newborn generated by the female.
calculate_demographic <- function(
    shape, animals, int, beta, beta_sd, trait_values
) {
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd)
    demo_values <- int + (beta_animals * trait_values)
  }
  return(demo_values)
}





#################################################
#####Surviving/Transformation/New Life Steps#####
#################################################

#arguments
shape <- 'linear'
starting_animals <-1000 #it should be an even number
animals<- 1:starting_animals #half juvenile and half adult
trans_p <- 0.5
thr_age <- 4 #age limit


plastic_scenario <- function(years, #number of years we want to run the simulation
                         mean_t, #mean of simulated temperature
                         sd_t, #sd of the simulated temperature
                         int_trait, #intercept of the temp/trait linear dependency
                         beta_trait, #coeff. of the temp/trait linear dependency
                         sd_trait, #s.d. of the Gaussian error around the temp/trait linear dependency
                         int_demo, #intercept of the trait/demo linear dependency
                         beta_demo, #coeff. of the trait/demo linear dependency
                         sd_demo) #s.d. of the Gaussian error around the trait/demo linear dependency
{
  
temp_init <- rnorm(1, mean=mean_t, sd=sd_t)
#Initializing steps:
#function (shape, animals, int, beta, beta_sd, clim.val)
trait_values <- calculate_trait(shape, animals, int_trait, beta_trait, sd_trait, temp_init) 

#function (shape, animals, int, beta, beta_sd, trait_values)
demo_values <- calculate_demographic(shape, animals, int_demo, beta_demo, sd_demo , trait_values)

#plogis transform real values into probabilities, the higher the demographic value the higher the probability of surviving.
#A value of 0.97 or 97% means that there is a 97% chance of surviving.
surv <- plogis(demo_values) 

#I'm gonna create a matrix with the ID of the animal, its trait_value and demo_value, so than I keep track of all the details of them, It could be nice for further statistical analysis

table <- data.table(
  id = animals,
  trait = trait_values ,
  demo = demo_values,
  p_survival =surv,
  stage = rep(c("juvenile", "adult"), each = starting_animals/2),
  birth_year=0,
  year=0,
  status="alive",
  temp=temp_init
)


temperature <-rnorm(n=years, mean_t,sd_t)

for (current_year in 1:years){
  
  
#exit if the number of alive animals is 0
if (exists("alive") && nrow(alive) == 0) {
  break
}


temp<- temperature[current_year]



#Age mortality
aged_ids <- with(table, id[status == "alive" & (year - birth_year) == thr_age])


#Survival mortality
alive_ids <- which(table$status == "alive")
unfit_ids <- table$id[alive_ids[table$p_survival[alive_ids] < runif(length(alive_ids))]]



#Density dependence mortality
n_alive<- sum(table$status=="alive")
dd_number <- floor(plogis(n_alive*0.001, 10, 2.3) * n_alive)
dd_dead_ids <- if (dd_number > 0) sample(table$id[table$status=="alive"], dd_number) else integer(0)


#Total mortality (simultaneous)
total_dead_ids <- unique(c(aged_ids, unfit_ids, dd_dead_ids))




#############
##NEW YEAR!##
#############
table <- table |>
  mutate(
    status = if_else(id %in% total_dead_ids, "dead", status),
    year   = if_else(!(id %in% total_dead_ids) & status == "alive",
                     current_year, year))



#Following lines of code are commented for the scenario with no plasticity (trait are given solely at the birth)

#New year, new values in the total plastic scenario!
#All the animal that survived until this point will receive a new trait based on the current temp
#######
n_alive <- sum(table$status == "alive")
alive_ids<-table$id[table$status == "alive"]

new_trait_values <- calculate_trait(shape, 1:n_alive, int_trait, beta_trait, sd_trait, temp)
new_demo_values<- calculate_demographic(shape, 1:n_alive, int_demo, beta_demo, sd_demo, new_trait_values)
new_surv <- plogis(new_demo_values)

table$trait[alive_ids]      <- new_trait_values
table$demo[alive_ids]       <- new_demo_values
table$p_survival[alive_ids] <- new_surv
table$temp[alive_ids]       <- temp
#######


##Transformation##
#We calculate how many juvenile move to adult.
juv_rows <- which(table$status == "alive" & table$stage == "juvenile")
p_event<- runif(length(juv_rows)) < 0.5
juv_trans_id<- juv_rows[p_event]



#update their status to adult
table$stage[table$id %in% juv_trans_id] <- "adult"


##New life##
left_index <- nrow(table)
right_index <- left_index
adult_demo <- table$demo[table$status == "alive" & table$stage=="adult"]
#the process is still not fully deterministic. The number of new individual is a stochastic Poisson event with the exponential of the demographic value as mean.

if (length(adult_demo) > 0) {
  exp_values<- exp(adult_demo)
  right_index <- right_index + floor(sum(exp_values))
  new_juv <- (left_index+1):right_index
  #we elongate the table of the juvenile, the trait is given according to the same temperature of that year
  trait_values <- calculate_trait(shape, new_juv, int_trait, beta_trait, sd_trait, temp)
  demo_values<- calculate_demographic(shape, new_juv, int_demo, beta_demo, sd_demo , trait_values)
  surv <- plogis(demo_values)
  
  
  
  new_juv <- data.table(
    id = new_juv,
    trait = trait_values ,
    demo = demo_values,
    p_survival =surv,
    stage='juvenile',
    birth_year=current_year,
    year=current_year,
    status="alive",
    temp=temp
  )
  
  table <- rbindlist(list(table, new_juv), use.names = TRUE, fill = TRUE)}


} #end of the loop for each year-temperature

return(table)
}


#Commented stuff:

evo_plastic <- plastic_scenario(100,
                                0,0,
                                0,1,0,
                                0,1,0)

