set.seed(404)


# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialized set.seed(404)
library(dplyr)
library(data.table)


# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialize both juveniles and adults, but later only juveniles), the beta coefficient of the linear model, the standard deviation of beta (beta_sd), and a temperature value. It outputs randomly generated beta values (drawn from a Gaussian distribution centered on beta with standard deviation beta_sd) and assigns a trait to each newborn accordingly.
#The user has to provide the sd and the mean
calculate_trait <- function(
    shape, animals, int,beta, beta_sd, clim_val
) { 
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd) 
    trait_values <- int + (beta_animals * clim_val)
    
  } 
  return(trait_values)
}



#Same concept as the one before, we generate for each new animal a linear coefficient taken from a Gaussian distribution. It returns a demographic value that can be used both to calculate the probability of surviving or the number of newborn generated by the female.
calculate_demographic <- function(
    shape, animals, int, beta, beta_sd, trait_values
) {
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd)
    demo_values <- int + (beta_animals * trait_values)
  }
  return(demo_values)
}





#################################################
#####Surviving/Transformation/New Life Steps#####
#################################################

#arguments
shape <- 'linear'
starting_animals <-200 #it should be an even number
animals<- 1:starting_animals #half juvenile and half adult
trans_p <- 0.5
thr_age <- 4 #age limit


sur_tran_new <- function(years, #number of years we want to run the simulation
                         mean_t, #mean of simulated temperature
                         sd_t, #sd of the simulated temperature
                         int_trait, #intercept of the temp/trait linear dependency
                         beta_trait, #coeff. of the temp/trait linear dependency
                         sd_trait, #s.d. of the Gaussian error around the temp/trait linear dependency
                         int_demo, #intercept of the trait/demo linear dependency
                         beta_demo, #coeff. of the trait/demo linear dependency
                         sd_demo) #s.d. of the Gaussian error around the trait/demo linear dependency
{
  
temp_init <- rnorm(1, mean=mean_t, sd=sd_t)
#Initializing steps:
#function (shape, animals, int, beta, beta_sd, clim.val)
trait_values <- calculate_trait(shape, animals, int_trait, beta_trait, sd_trait, temp_init) 

#function (shape, animals, int, beta, beta_sd, trait_values)
demo_values <- calculate_demographic(shape, animals, int_demo, beta_demo, sd_demo , trait_values)

#plogis transform real values into probabilities, the higher the demographic value the higher the probability of surviving.
#A value of 0.97 or 97% means that there is a 97% chance of surviving.
surv <- plogis(demo_values) 

#I'm gonna create a matrix with the ID of the animal, its trait_value and demo_value, so than I keep track of all the details of them, It could be nice for further statistical analysis

table <- data.table(
  id = animals,
  trait = trait_values ,
  demo = demo_values,
  p_survival =surv,
  stage = rep(c("juvenile", "adult"), each = starting_animals/2),
  birth_year=0,
  year=0,
  status="alive",
  temp=temp_init
)


temperature <-rnorm(n=years, mean_t,sd_t)

for (current_year in 1:years){
  
  
#exit if the number of alive animals is 0
if (exists("alive") && nrow(alive) == 0) {
  break
}


temp<- temperature[current_year]

n_alive<- sum(table$status=="alive")

#Age mortality
aged_ids <- with(table, id[status == "alive" & (year - birth_year) == thr_age])


#Survival mortality
alive_ids <- which(table$status == "alive")
unfit_ids <- table$id[alive_ids[table$p_survival[alive_ids] < runif(length(alive_ids))]]



#Density dependence mortality
dd_number <- floor(plogis(n_alive*0.001, 10, 2.3) * n_alive)
dd_dead_ids <- if (dd_number > 0) sample(table$id[table$status=="alive"], dd_number) else integer(0)


#Total mortality (simultaneus)
total_dead_ids <- unique(c(aged_ids, unfit_ids, dd_dead_ids))




#############
##NEW YEAR!##
#############
table <- table |>
  mutate(
    status = if_else(id %in% total_dead_ids, "dead", status),
    year   = if_else(!(id %in% total_dead_ids) & status == "alive",
                     current_year, year))



#This line are commented for the scenario with 0 plasticity (trait are given solely at the birt)
# #New year, new values!
# #All the animal that survived until this point will receive a new trait based on the current temp.
# n_alive <- sum(table$status == "alive")   
# 
# new_trait_values <- calculate_trait(shape, 1:n_alive, int_trait, beta_trait, sd_trait, temp)
# new_demo_values<- calculate_demographic(shape, 1:n_alive, int_demo, beta_demo, sd_demo , new_trait_values)
# new_surv <- plogis(new_demo_values)

# alive_ids<-table$id[table$status == "alive"]
# table$trait[alive_ids]      <- new_trait_values
# table$demo[alive_ids]       <- new_demo_values
# table$p_survival[alive_ids] <- new_surv
# table$temp[alive_ids]       <- temp



##Transformation##
#We calculate how many juvenile move to adult.
juv_rows <- which(table$status == "alive" & table$stage == "juvenile")
p_event<- runif(length(juv_rows)) < 0.5
juv_trans_id<- juv_rows[p_event]



#update their status to adult
table$stage[table$id %in% juv_trans_id] <- "adult"



##New life##
left_index <- nrow(table)
right_index <- left_index
adult_demo <- table$demo[table$status == "alive" & table$stage=="adult"]
#the process is still not fully deterministic. The number of new individual is a stochastic Poisson event with the exponential of the demographic value as mean.

if (sum(adult_demo) > 0)
{
  
  exp_values<- exp(adult_demo)
  right_index <- right_index + floor(sum(exp_values))
  new_juv <- (left_index+1):right_index
  #we elongate the table of the juvenile, the trait is given according to the same temperature of that year
  trait_values <- calculate_trait(shape, new_juv, int_trait, beta_trait, sd_trait, temp)
  demo_values<- calculate_demographic(shape, new_juv, int_demo, beta_demo, sd_demo , trait_values)
  surv <- plogis(demo_values)
  
  
  
  new_juv <- data.table(
    id = new_juv,
    trait = trait_values ,
    demo = demo_values,
    p_survival =surv,
    stage='juvenile',
    birth_year=current_year,
    year=current_year,
    status="alive",
    temp=temp
  )
  
  table <- rbindlist(list(table, new_juv), use.names = TRUE, fill = TRUE)
}
  
  
} #end of the loop for each year-temperature

return(table)
}


#This function takes as input the table of the simulation and returns another table with a count of the animals alive in the summer of each year.
#With summer I intend the period between the reproduction event and the three animal-reduction events during the same year.

alive_animals <- function(table){
  years <- max(table$year)
  alive <- c()
  
  for (i in 0:years) {
    count <- table[birth_year <= i & year >= i, .N] #.N is a special data.table symbol that just returns the number of rows in the subset
    alive <- c(alive, count)
  }
  
  summary_table <- data.frame(
    year = 0:years,
    alive = alive
  )
  return (summary_table)}


evo<- sur_tran_new(100,         #years
                   0.2, 1,  #temperature
                   0, 0.55, 0.2, #trait
                   0, 1, 0)

alive<-alive_animals(evo)  #demo)


#this function simply enough run n_sim simulations and of each one take the count of alive animals during the last year, if ==0 the population is counted as extinct.
#If the population is not extinct it averages the final count of individuals among simulations.
run_simulations <-function(nsim,
                           years,
                           mean_t,
                           sd_t,
                           int_trait,
                           beta_trait,
                           sd_trait,
                           int_demo,
                           beta_demo,
                           sd_demo)
{
  
  results <- tibble()
  
  for (i in 1:nsim) {
    evolution <- sur_tran_new(years=years,
                              mean_t=mean_t,
                              sd_t=sd_t,
                              int_trait=int_trait,
                              beta_trait=beta_trait,
                              sd_trait=sd_trait,
                              int_demo=int_demo,
                              beta_demo=beta_demo,
                              sd_demo=sd_demo)
    
    vector_alive <- alive_animals(evolution) |> pull(alive)
    years_with_animals<-length(vector_alive)-1
    sim_df <- tibble(
      year = 0:years_with_animals,
      simulation = i,
      alive = vector_alive
    )
    results <- bind_rows(results, sim_df)
  }
  
  return(results)
}

#coefficient of variation is the standart deviation over mean. This function returns a vector with a c.v. for each simulation. 
coefficient_of_variation<- function(table){
  cv<- table |>
    group_by(simulation) |>
    summarise(cv= sd(alive)/mean(alive)) |> pull()
  return(cv)
}

#function that returns a table with the count of extinction after all the simulations
extinct_count <- function(table){
  count_extinct<- table |>
    group_by(simulation) |>
    summarise(extinct = n() < 101) |> #when we have less than 101 rows it means they get extinct before time.
    summarise(total_extinct = sum(extinct)) |> pull()
  return(count_extinct)}


####################
#PLOTTING FUNCTIONS#
####################

#Takes one simulation table and it returns a plot with the log count of alive animals over years
make_a_plot <- function(df){
  ggplot(df, aes(x = year, y = log10(alive))) +
    geom_point(size = 2) +
    geom_line(alpha = 0.6) +
    labs(
      x = "Year",
      y = "Log Number of Individuals Alive"
    ) +
    ggtitle("Log Count of Animals over years") +
    theme_minimal()+
    theme(
      plot.title = element_text(size = 20, face = "bold"),   # title size
      axis.title.x = element_text(size = 16),                # x-axis label size
      axis.title.y = element_text(size = 16))
}


#This function takes as input a dataframe with all the count of alive animal for each year of each simulations and returns a plot. On the X axis the years and on the Y axis the logarithm of the count of alive animals for that year.
#It uses colors to differentiate simulations, don't run with more than 20 simulations.
make_a_plot_sim <- function(df){
  ggplot(df, aes(x = year, y = log10(alive), group = simulation, color = as.factor(simulation))) +
    geom_point(size = 2) +
    geom_line(alpha = 0.6) +
    labs(
      x = "Year",
      y = "Log Number of Individuals Alive",
      color = "Simulation"
    ) +
    ggtitle("Log Count of Animals over years") +
    theme_minimal()+
    theme(
      plot.title = element_text(size = 20, face = "bold"),   # title size
      axis.title.x = element_text(size = 16),                # x-axis label size
      axis.title.y = element_text(size = 16))
}



#Commented stuff:



# alive_df<-alive_animals(evo)
# vector_alive <- alive_animals(evo) |> select(alive)

# final<-run_simulations( 5, #number of simulations
#                         20, #years of the simulation
#                         0.3, 0.5, #climate mean and s.d.
#                         0, 1, 0.2, #trait int. mean and s.d.
#                         0, 1, 0.2) #demo int. mean and s.d.

# saveRDS(alive_df, "data/k_1.RDS")
