library(dplyr)

set.seed(42)
#We could for example start with 200 animals, 100 juvenile and 100 adults
shape <- 'linear'
ani_j <-1:100
ani_a <- 101:200
temp <- 0



# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialize both juveniles and adults, but later only juveniles), the beta coefficient of the linear model, the standard deviation of beta (beta_sd), and a temperature value. It outputs randomly generated beta values (drawn from a Gaussian distribution centered on beta with standard deviation beta_sd) and assigns a trait to each newborn accordingly.
calculate_trait <- function(
    shape, animals, int,beta, beta_sd, clim.val
) { 
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd) #nico: here the user has to provide the sd and the mean
    trait_values <- int + (beta_animals * clim.val)
    
  } 
  return(trait_values)
}


#Same concept as the one before, we generate for each new animal a linear coefficient taken from a Gaussian distribution. It returns a demographic value that can be used both to calculate the probability of surviving or the number of newborn generated by the female.
calculate_demographic <- function(
    shape, animals, int, beta, beta_sd, trait_values
) {
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd)
    demo_values <- int + (beta_animals * trait_values)
}
  return(demo_values)
}

###########################
####INITIALIZING STEP######
###########################

#function (shape, animals, int, beta, beta_sd, clim.val)
trait_values_j <- calculate_trait(shape, ani_j, 0, 1, 1,temp) 
trait_values_a <- calculate_trait(shape, ani_a, 0, 1, 1,temp)


#function (shape, animals, int, beta, beta_sd, trait_values)
demo_values_j <- calculate_demographic(shape, ani_j, 0, 0.5, 0.1 , trait_values_j)
demo_values_a <- calculate_demographic(shape, ani_a, 0, 0.5, 0.1 , trait_values_a)


#plogis transform real values into probabilities, the higher the demographic value the higher the probability of surviving.
#A value of 0.97 or 97% means that there is a 97% chance of surviving.
surv_j <- plogis(demo_values_j) 
surv_a <- plogis(demo_values_a)

#I'm gonna create a matrix with the ID of the animal, its trait_value and demo_value, so than I keep track of all the details of them, It could be nice for further statistical analysis
table_j <- data.frame(
  id = ani_j,
  trait = trait_values_j ,
  demo = demo_values_j,
  p_survival =surv_j,
  stage='juvenile'
)

table_a <- data.frame(
  id = ani_a,
  trait = trait_values_a ,
  demo = demo_values_a,
  p_survival =surv_a,
  stage= 'adult'
)


#############################################
#####Surviving/Transformation/New Life Steps#####
#############################################
s_p=200 #for the index
big_function <- function(temperature){
  
  for (temp in temperature){
  
#Surviving
surv_event_j <- runif(n=length(ani_j), min = 0, max = 1) 
surv_event_a <- runif(n=length(ani_a), min = 0, max = 1)

survived_j <- surv_event_j < surv_j
survived_a <- surv_event_a < surv_a

table_j <- table_j[survived_j,]
table_a <- table_a[survived_a,]

#Transformation
#now we calculate how many juvenile move to adult, in practice how many row of the juvenile table will be added to the adult table.
transformation <- 0.5
trans_event <- runif(table_j$id, min = 0, max = 1)
transformed <- trans_event < transformation 

table_a <- bind_rows(
  table_a,
  table_j |>
    filter(transformed) |>
    mutate(stage = ifelse(stage == "juvenile", "adult", stage))
)

table_j <- filter(table_j, !transformed)
  
#New life
#Here we use the same computed demographic trait to compute the number of new born, for each individual.
#repr_adu_trans <- exp(repr_adu_lin)


s_n=s_p#used for keeping track of the new indexes of the juvenile
#in this approach there is no inheritance so we can just easily sum up all the new babies
for (adult_demo in table_a$demo){
  s_n<- s_n+ round(exp(adult_demo))
}

ani_n <-(s_p+1:s_n)
s_p <- s_n
#we elongate the table of the juvenile, the trait is given according to the same temperature value

trait_values_n <- calculate_trait(shape, ani_n, 0, 0.5, 0.1, temp)
demo_values_n <- calculate_demographic(shape, ani_n, 0, 0.5, 0.1 , trait_values_n)
surv_n <- plogis(demo_values_n)

table_n <- data.frame(
  id = ani_n,
  trait = trait_values_n ,
  demo = demo_values_n,
  p_survival =surv_n,
  stage='newborn'
)

table_j <- rbind(table_j, table_n)

  } #end of the loop for each year-temperature
  table_tot <- rbind(table_j, table_a)
}

table_tot <- big_function(c(20))

