library(dplyr)

# set.seed(11)


# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialize both juveniles and adults, but later only juveniles), the beta coefficient of the linear model, the standard deviation of beta (beta_sd), and a temperature value. It outputs randomly generated beta values (drawn from a Gaussian distribution centered on beta with standard deviation beta_sd) and assigns a trait to each newborn accordingly.
#The user has to provide the sd and the mean
calculate_trait <- function(
    shape, animals, int,beta, beta_sd, clim_val
) { 
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd) 
    trait_values <- int + (beta_animals * clim_val)
    
  } 
  return(trait_values)
}



#Same concept as the one before, we generate for each new animal a linear coefficient taken from a Gaussian distribution. It returns a demographic value that can be used both to calculate the probability of surviving or the number of newborn generated by the female.
calculate_demographic <- function(
    shape, animals, int, beta, beta_sd, trait_values
) {
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd)
    demo_values <- int + (beta_animals * trait_values)
}
  return(demo_values)
}





#############################################
#####Surviving/Transformation/New Life Steps#####
#############################################

#arguments
shape <- 'linear'
starting_animals <-200 #it should be an even number
animals<- 1:starting_animals #half juvenile and half adult
temp <- 0.5
trans_p <- 0.5
thr_age <- 4 #age limit


sur_tran_new <- function(years, #number of years we want to run the simulation
                         mean_t, #mean of simulated temperature
                         sd_t, #sd of the simulated temperature
                         int_trait, #intercept of the temp/trait linear dependency
                         beta_trait, #coeff. of the temp/trait linear dependency
                         sd_trait, #s.d. of the Gaussian error around the temp/trait linear dependency
                         int_demo, #intercept of the trait/demo linear dependency
                         beta_demo, #coeff. of the trait/demo linear dependency
                         sd_demo) #s.d. of the Gaussian error around the trait/demo linear dependency
{
  


#Initializing steps:
#function (shape, animals, int, beta, beta_sd, clim.val)
trait_values <- calculate_trait(shape, animals, int_trait, beta_trait, sd_trait, temp) 

#function (shape, animals, int, beta, beta_sd, trait_values)
demo_values <- calculate_demographic(shape, animals, int_demo, beta_demo, sd_demo , trait_values)

#plogis transform real values into probabilities, the higher the demographic value the higher the probability of surviving.
#A value of 0.97 or 97% means that there is a 97% chance of surviving.
surv <- plogis(demo_values) 

#I'm gonna create a matrix with the ID of the animal, its trait_value and demo_value, so than I keep track of all the details of them, It could be nice for further statistical analysis

table <- data.frame(
  id = animals,
  trait = trait_values ,
  demo = demo_values,
  p_survival =surv,
  stage = rep(c("juvenile", "adult"), each = starting_animals/2),
  birth_year=0,
  year=0,
  status="alive",
  temp=temp
)


temperature <-rnorm(n=years, mean_t,sd_t)

for (current_year in 1:years){
  
  #exit if the number of alive animals is 0
  if (exists("alive") && nrow(alive) == 0) {
    break
  }

  
temp<- temperature[current_year]



#remove aged animals
#start the function by grabbing only the animals that survived until the previous year

aged_id <-which(table$status =="alive" & (table$year - table$birth_year) == thr_age)
table$status[aged_id] <- "dead"




#remove based animal based on trait-demographics
alive <- table|> filter(status == "alive")
surv_event <- runif(n=nrow(alive), min=0, max=1)
survived <- alive$p_survival > surv_event
survivor_ids <- alive$id[survived]
dead_ids <- alive$id[!survived]


# Update their year in the original table
table$status[table$id %in% survivor_ids] <- "alive"
table$status[table$id %in% dead_ids] <- "dead"
table$year[table$id %in% survivor_ids] <- current_year



#remove animals based on Demographic Dependencies
alive <- table |> filter(status == "alive")

dd_number <-floor(plogis(nrow(alive) * 0.001,
                         location=10,scale=2.3)
                  *nrow(alive))

if (dd_number > 0) {
  dd_dead_ids <- sample(alive$id, size = dd_number)
  table$status[table$id %in% dd_dead_ids] <- "dead"
}



##Transformation##
#We calculate how many juvenile move to adult.


juv <- table|> filter(status=="alive", stage=="juvenile")
trans_event <- runif(n=nrow(juv), min=0, max=1)
transformed <- trans_event < trans_p
juv_trans_id <-juv$id[transformed]



#update their status on the main table
table$stage[table$id %in% juv_trans_id] <- "adult"



  
##New life##


left_index <- nrow(table)
right_index <- left_index
adult<- table|> filter(status=="alive", stage=="adult")
#the process is still not fully deterministic. The number of new individual is a stochastic Poisson event with the exponential of the demographic value as mean.
if (nrow(adult) > 0)
  {
  exp_values<- exp(adult$demo)
  right_index <- right_index + sum(rpois(nrow(adult), lambda = exp_values))
  #this because rpois has two arguments n and the mean, in our case the mean are the vector with the exponential of the demographic values and n is the number of alive adult.
  new_juv <- (left_index+1):right_index
  
  #we elongate the table of the juvenile, the trait is given according to the same temperature of that year
  trait_values <- calculate_trait(shape, new_juv, int_trait, beta_trait, sd_trait, temp)
  demo_values<- calculate_demographic(shape, new_juv, int_demo, beta_demo, sd_demo , trait_values)
  surv <- plogis(demo_values)
  
  new_juv <- data.frame(
    id = new_juv,
    trait = trait_values ,
    demo = demo_values,
    p_survival =surv,
    stage='juvenile',
    birth_year=current_year,
    year=current_year,
    status="alive",
    temp=temp
  )
  table<- rbind(table,new_juv)
}

  } #end of the loop for each year-temperature

return(table)
}


#This function takes as input the table of the simulation and returns another table with a count of the animals alive in the summer of each year.
#With summer I intend the period between the reproduction event and the three animal-reduction events during the same year. 
alive_animals <- function(table){
  
  temp <- table |>
    arrange(id) |>
    select(temp)|>
    unique()
  #the temperature values are all unique so I can use them to track the years.
  years <- nrow(temp)-1

  
  alive <- c()
  for (i in 0:years) {
    count <- nrow(table |> filter(birth_year <= i & year >= i))
    alive <- c(alive, count)
  }
  
  summary_table <- data.frame(
    year = 0:years,
    alive = alive,      
    temp = temp         
  )
  return (summary_table)}


#this function simply enough run n_sim simulations and of each one take the count of alive animals during the last year, if ==0 the population is counted as extinct.
#If the population is not extinct it averages the final count of individuals among simulations.
run_simulations <-function(nsim,
                           years,
                           mean_t,
                           sd_t,
                           int_trait,
                           beta_trait,
                           sd_trait,
                           int_demo,
                           beta_demo,
                           sd_demo)
                           {

results <- tibble()

for (i in 1:nsim) {
  evolution <- sur_tran_new(years=years,
                              mean_t=mean_t,
                              sd_t=sd_t,
                              int_trait=int_trait,
                              beta_trait=beta_trait,
                              sd_trait=sd_trait,
                              int_demo=int_demo,
                              beta_demo=beta_demo,
                              sd_demo=sd_demo)
   
  vector_alive <- alive_animals(evolution) |> pull(alive)
  years_with_animals<-length(vector_alive)-1
  sim_df <- tibble(
    year = 0:years_with_animals,
    simulation = i,
    alive = vector_alive
  )
  results <- bind_rows(results, sim_df)
}

return(results)
}


# final<-run_simulations( 1, #number of simulations
#                         200, #years of the simulation
#                         0.3, 0.5, #climate mean and s.d.
#                         0, 1, 0.2, #trait int. mean and s.d.
#                         0, 1, 0.2) #demo int. mean and s.d.


#Commented stuff:

# evo<- sur_tran_new(100,#years
#                   -1,0.5,#temperature
#                    0,1,0.2,#trait
#                  0,1,0.2)#demo
# 
# alive_df<-alive_animals(evo)
# vector_alive <- alive_animals(evo) |> select(alive)

# saveRDS(alive_df, "data/k_1.RDS")
