library(dplyr)

set.seed(42)

shape <- 'linear'
animals<- 1:200 #first 100 juvenile and second 100 adults
temp <- 1



# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialize both juveniles and adults, but later only juveniles), the beta coefficient of the linear model, the standard deviation of beta (beta_sd), and a temperature value. It outputs randomly generated beta values (drawn from a Gaussian distribution centered on beta with standard deviation beta_sd) and assigns a trait to each newborn accordingly.
#The user has to provide the sd and the mean
calculate_trait <- function(
    shape, animals, int,beta, beta_sd, clim.val
) { 
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd) 
    trait_values <- int + (beta_animals * clim.val)
    
  } 
  return(trait_values)
}


#Same concept as the one before, we generate for each new animal a linear coefficient taken from a Gaussian distribution. It returns a demographic value that can be used both to calculate the probability of surviving or the number of newborn generated by the female.
calculate_demographic <- function(
    shape, animals, int, beta, beta_sd, trait_values
) {
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd)
    demo_values <- int + (beta_animals * trait_values)
}
  return(demo_values)
}

###########################
####INITIALIZING STEP######
###########################

#function (shape, animals, int, beta, beta_sd, clim.val)
trait_values <- calculate_trait(shape, animals, 0, 1, 1,temp) 

#function (shape, animals, int, beta, beta_sd, trait_values)
demo_values <- calculate_demographic(shape, animals, 0, 0.5, 0.1 , trait_values)

#plogis transform real values into probabilities, the higher the demographic value the higher the probability of surviving.
#A value of 0.97 or 97% means that there is a 97% chance of surviving.
surv <- plogis(demo_values) 

#I'm gonna create a matrix with the ID of the animal, its trait_value and demo_value, so than I keep track of all the details of them, It could be nice for further statistical analysis

table <- data.frame(
  id = animals,
  trait = trait_values ,
  demo = demo_values,
  p_survival =surv,
  stage = rep(c("juvenile", "adult"), each = 100),
  birth=0,
  year=0,
  status="alive"
)



#############################################
#####Surviving/Transformation/New Life Steps#####
#############################################

sur_tras_new <- function(years){

temperature <-rnorm(n=years, 0,1)

for (current_year in 1:years){
  
temp<- temperature[current_year]

##Surviving##

#start the function by grabbing only the animals that survived until the previous year
alive <- table|> filter(status == "alive")


#Check who will survive (this year!) and who not
surv_event <- runif(n=nrow(alive), min=0, max=1)
survived <- alive$p_survival > surv_event
survivor_ids <- alive$id[survived]
dead_ids <- alive$id[!survived]

# Update their year in the original table
table$status[table$id %in% dead_ids] <- "dead"
table$status[table$id %in% survivor_ids] <- "alive"
table$year[table$id %in% survivor_ids] <- current_year




##Transformation##
#We calculate how many juvenile move to adult.
trans_p <- 0.5
juv <- table|> filter(stage=="juvenile")
trans_event <- runif(n=juv, min=0, max=1)
transformed <- trans_p > trans_event
juv_trans_id <-juv$id[transformed]

#update their status
table$stage[table$id %in% juv_trans_id] <- "adult"


  
##New life##

#Compute number of newborn (no inheritance from parents)
#is there a nicer way to do this??
s_p <- nrow(table)
s_n <- s_p
adult<- table|> filter(stage=="adult")
s_n <- s_n + round(sum(exp(adult$demo)))
new_juv <- (s_p+1):s_n
s_p <- s_n

#we elongate the table of the juvenile, the trait is given according to the same temperature of that year

trait_values <- calculate_trait(shape, new_juv, 0, 0.5, 0.1, temp)
demo_values<- calculate_demographic(shape, new_juv, 0, 0.5, 0.1 , trait_values)
surv <- plogis(demo_values)

new_juv <- data.frame(
  id = new_juv,
  trait = trait_values ,
  demo = demo_values,
  p_survival =surv,
  stage='juvenile',
  birth=current_year,
  year=current_year,
  status="alive"
)
table<- rbind(table,new_juv)
  } 
#end of the loop for each year-temperature
return(table)
}

table <- sur_tras_new(years=5) #this grows exponentially until I write the demo dependencies
dead<- table|> filter(status=="dead")
strange<- dead|>filter((dead$year-dead$birth)==-3)##???

#oki there are still some bugs ehehe
