#library(dplyr)

set.seed(42)


# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialize both juveniles and adults, but later only juveniles), the beta coefficient of the linear model, the standard deviation of beta (beta_sd), and a temperature value. It outputs randomly generated beta values (drawn from a Gaussian distribution centered on beta with standard deviation beta_sd) and assigns a trait to each newborn accordingly.
#The user has to provide the sd and the mean
calculate_trait <- function(
    shape, animals, int,beta, beta_sd, clim.val
) { 
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd) 
    trait_values <- int + (beta_animals * clim.val)
    
  } 
  return(trait_values)
}



#Same concept as the one before, we generate for each new animal a linear coefficient taken from a Gaussian distribution. It returns a demographic value that can be used both to calculate the probability of surviving or the number of newborn generated by the female.
calculate_demographic <- function(
    shape, animals, int, beta, beta_sd, trait_values
) {
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd)
    demo_values <- int + (beta_animals * trait_values)
}
  return(demo_values)
}





#############################################
#####Surviving/Transformation/New Life Steps#####
#############################################

sur_tran_new <- function(years){
  
shape <- 'linear'
starting_animals <- 200 #even number
animals<- 1:starting_animals #half juvenile and half adult
temp <- 1
###########################
####INITIALIZING STEP######
###########################

#function (shape, animals, int, beta, beta_sd, clim.val)
trait_values <- calculate_trait(shape, animals, 0, 1, 0.2,temp) 

#function (shape, animals, int, beta, beta_sd, trait_values)
demo_values <- calculate_demographic(shape, animals, 0, 1, 0.2 , trait_values)

#plogis transform real values into probabilities, the higher the demographic value the higher the probability of surviving.
#A value of 0.97 or 97% means that there is a 97% chance of surviving.
surv <- plogis(demo_values) 

#I'm gonna create a matrix with the ID of the animal, its trait_value and demo_value, so than I keep track of all the details of them, It could be nice for further statistical analysis

table <- data.frame(
  id = animals,
  trait = trait_values ,
  demo = demo_values,
  p_survival =surv,
  stage = rep(c("juvenile", "adult"), each = starting_animals/2),
  birth=0,
  year=0,
  status="alive",
  temp=temp
)

  
temperature <-rnorm(n=years, 0,1)

for (current_year in 1:years){
  
temp<- temperature[current_year]

##Surviving##

#start the function by grabbing only the animals that survived until the previous year
alive <- table|> filter(status == "alive")



#Check who will survive (this year!) and who not
surv_event <- runif(n=nrow(alive), min=0, max=1)
survived <- alive$p_survival > surv_event
survivor_ids <- alive$id[survived]
dead_ids <- alive$id[!survived]


# Update their year in the original table
table$status[table$id %in% survivor_ids] <- "alive"
table$status[table$id %in% dead_ids] <- "dead"
table$year[table$id %in% survivor_ids] <- current_year

#Add Demographic Dependencies
alive <- table |> filter(status == "alive")
b = 0.0001
dd_number <-floor(exp(b * nrow(alive)))
dd_dead_ids <- sample(alive$id,size=dd_number)
table$status[table$id %in% dd_dead_ids] <- "dead"





##Transformation##
#We calculate how many juvenile move to adult.

trans_p <- 0.5
juv <- table|> filter(status=="alive", stage=="juvenile")
trans_event <- runif(n=juv, min=0, max=1)
transformed <- trans_event > trans_p
juv_trans_id <-juv$id[transformed]



#update their status on the main table
table$stage[table$id %in% juv_trans_id] <- "adult"


  
##New life##

#Compute number of newborn (no inheritance trait from parents)

left_index <- nrow(table)
right_index <- left_index
adult<- table|> filter(status=="alive", stage=="adult")
right_index <- right_index + round(sum(exp(adult$demo)))
new_juv <- (left_index+1):right_index


#we elongate the table of the juvenile, the trait is given according to the same temperature of that year

trait_values <- calculate_trait(shape, new_juv, 0, 1, 0.2, temp)
demo_values<- calculate_demographic(shape, new_juv, 0, 1, 0.2 , trait_values)
surv <- plogis(demo_values)

new_juv <- data.frame(
  id = new_juv,
  trait = trait_values ,
  demo = demo_values,
  p_survival =surv,
  stage='juvenile',
  birth=current_year,
  year=current_year,
  status="alive",
  temp=temp
)
table<- rbind(table,new_juv)
  } 
#end of the loop for each year-temperature
return(table)
}

table <- sur_tran_new(years=20) #why sometimes this breaks??





