set.seed(42)
#We could for example start with 200 animals, 100 juvenile and 100 adults
shape <- 'linear'
ani_j <-1:100
ani_a <- 101:200
temp <- 2



# This function takes as input the shape of the distribution (currently only linear), a vector of animals (first I initialize both juveniles and adults, but later only juveniles), the beta coefficient of the linear model, the standard deviation of beta (beta_sd), and a temperature value. It outputs randomly generated beta values (drawn from a Gaussian distribution centered on beta with standard deviation beta_sd) and assigns a trait to each newborn accordingly.
calculate_trait <- function(
    shape, animals, int,beta, beta_sd, clim.val
) { 
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd) #nico: here the user has to provide the sd and the mean
    trait_values <- int + (beta_animals * clim.val)
    
  } 
  return(trait_values)
}


#Same concept as the one before, we generate for each new animal a linear coefficient taken from a Gaussian distribution. It returns a demographic value that can be used both to calculate the probability of surviving or the number of newborn generated by the female.
calculate_demographic <- function(
    shape, animals, int, beta, beta_sd, trait_values
) {
  if (shape == "linear") {
    n_animals <- length(animals)
    beta_animals <- rnorm(n_animals,mean=beta,sd=beta_sd)
    demo_values <- int + (beta_animals * trait_values)
}
  return(demo_values)
}

###########################
####INITIALIZING STEP######
###########################

#function (shape, animals, int, beta, beta_sd, clim.val)
trait_values_j <- calculate_trait(shape, ani_j, 0, 1, 1,temp) 
trait_values_a <- calculate_trait(shape, ani_a, 0, 1, 1,temp)


#function (shape, animals, int, beta, beta_sd, trait_values)
demo_values_j <- calculate_demographic(shape, ani_j, 0, 1, 1 , trait_values_j)
demo_values_a <- calculate_demographic(shape, ani_a, 0, 1, 1 , trait_values_a)


#plogis transform real values into probabilities, the higher the demographic value the higher the probability of surviving.
#A value of 0.97 or 97% means that there is a 97% chance of surviving.
surv_j <- plogis(demo_values_j) 
surv_a <- plogis(demo_values_a)

#I'm gonna create a matrix with the ID of the animal, its trait_value and demo_value, so than I keep track of all the details of them, It could be nice for further statistical analysis
table_j <- data.frame(
  id = ani_j,
  trait = trait_values_j ,
  demo = demo_values_j,
  p_survival =surv_j
)

#########################################
#####Death/Life/Transformation steps#####
#########################################

transformation <- 0.5



surv_event_j <- runif(n=length(ani_j), min = 0, max = 1) 
surv_event_a <- runif(n=length(ani_a), min = 0, max = 1)

survived_j <- surv_event_j < surv_j
survived_a <- surv_event_a < surv_a

table_j <- table_j[survived_j,]
sum(survived_j)

#use rbind
#TODO maybe it may be nicer to put all this into a function.


trans_event <- runif(demo_values_j, min = 0, max = 1)
transformed <- trans_event < transformation

# survived <- life_events < demo_values_p #if the value of the random variable is smaller than the survival probability the animal survives






